# This workflow will set up the oc CLI in your GitHub Action workflow and deploy your application to your OpenShift cluster.
#
# This workflow assumes you already have access to an OpenShift cluster.
# For instructions to get started with OpenShift see https://www.openshift.com/try
#
# To configure this workflow:
#
# 1. Set up a secret in your repository named OPENSHIFT_SERVER_URL with the value of your OpenShift server URL.
# 
# 2. Set up another secret named API_TOKEN with the value of a valid token to authenticate to OpenShift.
#
# 3. Change the values for the PROJECT and APP_NAME environment variables  (below).
#
# For more information on the OpenShift Action, refer to https://github.com/redhat-developer/openshift-actions

name: CI Pipeline  
on:  
  push:  
    branches: [ "main" ]  # Only triggers on pushes to `main`  
  pull_request:           # Optional: Adds PR trigger for testing  
    branches: [ "main" ]  

jobs:  
  test:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v4  

      - name: Setup Node.js  
        uses: actions/setup-node@v4  
        with:  
          node-version: 20  

      - name: Install dependencies (realistic mock)  
        run: |  
          if [ -f package.json ]; then  
            npm ci  
          else  
            echo "No package.json found. Skipping install."  
          fi  

      - name: Run tests (mock)  
        run: |  
          echo "Running tests... (this is a mock)"  
          echo "✅ All tests passed!"  

      - name: Print deployment warning  
        if: github.ref == 'refs/heads/main'  
        run: echo "🚀 This would deploy to production!"
